# Generated by Django 3.2.6 on 2021-08-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(default='', max_length=10)),
                ('mobile_no_1', models.CharField(max_length=15)),
                ('mobile_no_2', models.CharField(max_length=15)),
                ('mobile_no_3', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('profession', models.CharField(max_length=30)),
                ('customer_source', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('additional_notes', models.TextField()),
                ('bank_details', models.TextField()),
                ('time_zone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('listing_unit_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_title', models.CharField(max_length=50)),
                ('session_description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.TextField()),
                ('notes', models.TextField()),
                ('duration', models.TextField(max_length=10)),
                ('repeat', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.TextField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=40)),
                ('customer_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fb_app.customer')),
                ('product_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fb_app.product')),
                ('session_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fb_app.session')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_title', models.CharField(max_length=50)),
                ('sale_description', models.TextField()),
                ('sale_price', models.FloatField()),
                ('package_maturity', models.CharField(max_length=20)),
                ('no_of_sessions', models.FloatField()),
                ('session_frequency', models.CharField(max_length=50)),
                ('session_frequency_unit', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fb_app.customer')),
                ('product_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fb_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_title', models.CharField(max_length=50)),
                ('payment_description', models.TextField()),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fb_app.customer')),
                ('sale_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fb_app.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_title', models.CharField(max_length=50)),
                ('expense_description', models.TextField()),
                ('expense_amount', models.IntegerField()),
                ('expense_allocation_flag', models.CharField(max_length=50)),
                ('expense_type', models.CharField(max_length=40)),
                ('package_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fb_app.customer')),
            ],
        ),
    ]
