# Generated by Django 3.2.6 on 2021-08-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
